name: daravel
description: A Dart framework inspired by Laravel.
version: 1.0.0
publish_to: 'none'
repository: https://github.com/dart-daravel/daravel-core

environment:
  sdk: ^3.5.2

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  daravel_core:
    path: ../

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
