name: daravel_core
description: 'A new Flutter package project.'
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.1
  shelf_router: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
