name: publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    environment: pub.dev

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - uses: flutter-actions/setup-pubdev-credentials@v1

      - name: Delete Documentation
        run: rm -rf doc

      - name: Publish Package
        run: flutter pub publish --force